### ISSUE TITLE
Error: Cannot find module './lib/'

### ISSUE THREAD

**Issue by CircuitLord** [Superd22/spectrum-bot#10]
I don't know if I'm just doing something wrong or something, but no matter what I do, I always get

> Error: Cannot find module './lib/'
>     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:580:15)
>     at Function.Module._load (internal/modules/cjs/loader.js:506:25)
>     at Module.require (internal/modules/cjs/loader.js:636:17)
>     at require (internal/modules/cjs/helpers.js:20:18)

I installed all the build tools needed, and it seems to build fine every time I install it, but anytime I try to do anything with it, it crashes. Tried with Node v8 and v10.

Again, maybe I'm just missing something obvious, dunno.

Thanks.

**Comment by Superd22** [comment]
Hey @CircuitLord. There's an issue with the CD currently.

just npm run build *inside* the `node_modules/spectrum-bot/` directory will fix your issue

**Comment by Superd22** [comment]
The issue should now be fixed with new CI/CD for ^2.0.0 feel free to re-open if that's not the case.
